let user=null, student=null, posts=[], messages=[];
const $=id=>document.getElementById(id);const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(window.__t);window.__t=setTimeout(()=>$('toast').classList.add('hidden'),2400)}
function showPage(id){document.querySelectorAll('.module').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));const n={home:['My Portal','Your TeraByte Computer Academy student dashboard'],posts:['Blog & Notices','Academy announcements and learning updates'],messages:['Messages','Your private and academy-wide messages'],profile:['My Profile','Your registered academy information'],idcard:['My ID Card','Generate and download your student ID card']};$('pageTitle').textContent=n[id][0];$('pageSub').textContent=n[id][1];window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('[data-page-jump]').forEach(b=>b.onclick=()=>showPage(b.dataset.pageJump));$('logoutBtn').onclick=logout;
async function init(){user=await requireRole('student');if(!user)return;const r=await SB().from('students').select('*').eq('user_id',user.id).single();if(r.error)throw r.error;student=r.data;const p=await SB().from('posts').select('*').eq('published',true).order('created_at',{ascending:false});if(p.error)throw p.error;posts=p.data||[];const m=await SB().from('messages').select('*').or(`recipient_user_id.eq.${user.id},recipient_user_id.is.null`).order('created_at',{ascending:false});if(m.error)throw m.error;messages=m.data||[];renderAll()}
function renderAll(){const initial=(student.name||'S')[0].toUpperCase();$('studentTopName').textContent=student.name;$('studentTopCourse').textContent=student.course;$('studentAvatar').textContent=initial;$('homeAdmission').textContent=student.admission_no;$('homeCourse').textContent=student.course;$('homeDue').textContent=money(student.due_amount);$('homeUnread').textContent=messages.filter(m=>!m.read_at).length;renderPosts();renderMessages();renderProfile();renderIdCard()}
function postCard(p){return `<article class="post-item"><div class="post-meta"><span class="badge paid">ACADEMY</span><span>${new Date(p.created_at).toLocaleString('en-IN')}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.content).replace(/\n/g,'<br>')}</p></article>`}
function renderPosts(){const html=posts.length?posts.map(postCard).join(''):'<div class="empty">No announcements have been published yet.</div>';$('studentPosts').innerHTML=html;$('homePosts').innerHTML=posts.slice(0,3).map(postCard).join('')||'<div class="empty">No new notices.</div>'}
function messageCard(m){return `<article class="message-item ${m.read_at?'':'unread'}"><div class="post-meta"><span class="badge ${m.recipient_user_id?'partial':'active'}">${m.recipient_user_id?'PRIVATE':'ACADEMY'}</span><span>${new Date(m.created_at).toLocaleString('en-IN')}</span></div><h3>${esc(m.subject)}</h3><p>${esc(m.body).replace(/\n/g,'<br>')}</p>${!m.read_at?`<button class="btn secondary" onclick="markRead('${m.id}')">Mark as read</button>`:''}</article>`}
function renderMessages(){const html=messages.length?messages.map(messageCard).join(''):'<div class="empty">Your inbox is empty.</div>';$('studentMessages').innerHTML=html;$('homeMessages').innerHTML=messages.slice(0,3).map(messageCard).join('')||'<div class="empty">No messages.</div>'}
async function markRead(id){const {error}=await SB().from('messages').update({read_at:new Date().toISOString()}).eq('id',id).eq('recipient_user_id',user.id);if(error)toast(error.message);else{const m=messages.find(x=>x.id===id);if(m)m.read_at=new Date().toISOString();renderAll();toast('Message marked as read')}}window.markRead=markRead;
function renderProfile(){const items=[['Admission No.',student.admission_no],['Registration Date',student.registration_date],['Father / Guardian',student.father_name],['Contact',student.contact],['Email',student.email||'Not provided'],['Class / Level',student.class_level||'—'],['Batch / Session',student.batch||'—'],['Course',student.course],['Duration',student.duration],['Total Fees',money(student.total_fees)],['Fees Paid',money(student.paid)],['Due Amount',money(student.due_amount)],['Certificate',student.certificate_status],['Address',student.address||'Not provided']];$('profileGrid').innerHTML=items.map(([a,b])=>`<div class="detail"><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('')}
async function photoUrl(path){if(!path)return '';const {data,error}=await SB().storage.from('student-photos').createSignedUrl(path,3600);return error?'':data.signedUrl}
async function idCardHTML(){const url=await photoUrl(student.photo_path);return `<div id="studentIdCanvas" class="id-card-modern"><div class="id-top"><img src="logo.png" alt=""><h3>TeraByte Computer Academy</h3><p>LEARN • GROW • SUCCEED</p></div>${url?`<img class="id-photo" src="${esc(url)}" alt="Student photo">`:''}<div class="id-content"><h2>${esc(student.name)}</h2><div class="id-reg">${esc(student.admission_no)}</div><div class="id-row"><span>Course</span><strong>${esc(student.course)}</strong></div><div class="id-row"><span>Class</span><strong>${esc(student.class_level||'—')}</strong></div><div class="id-row"><span>Batch</span><strong>${esc(student.batch||'—')}</strong></div><div class="id-row"><span>Contact</span><strong>${esc(student.contact)}</strong></div></div><div class="id-footer">PROPERTY OF TERABYTE COMPUTER ACADEMY</div></div>`}
async function renderIdCard(){$('studentIdPreview').innerHTML=await idCardHTML()}
$('downloadMyId').onclick=async()=>{const canvas=await html2canvas($('studentIdCanvas'),{scale:3,useCORS:true,backgroundColor:'#fff',logging:false});const a=document.createElement('a');a.download=`${student.admission_no}_ID_Card.jpg`;a.href=canvas.toDataURL('image/jpeg',.95);a.click()};
init().catch(e=>toast(e.message||'Unable to load student portal'));
